# Generated by Django 6.1.1 on 2026-09-27 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_quantity', models.IntegerField(blank=True, null=True)),
                ('new_quantity', models.IntegerField(blank=True, null=True)),
                ('previous_stock_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_stock_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_updates', to='products.shopproduct')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
