# Generated by Django 6.1.1 on 2026-09-25 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=275, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('image_url', models.URLField(blank=True, default='')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('mL', 'Millilitre'), ('piece', 'Piece'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('box', 'Box'), ('bottle', 'Bottle'), ('pair', 'Pair')], max_length=20)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], db_index=True, default='in_stock', max_length=20)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('merchant_notes', models.TextField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shops.shop')),
            ],
            options={
                'db_table': 'shop_products',
                'ordering': ['price'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.UniqueConstraint(fields=('shop', 'product'), name='unique_shop_product'),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='non_negative_quantity'),
        ),
    ]
